[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/2026-05-02-coupe-du-monde-descalade-2026-le-guide-complet-du-circuit-international/index.html"
to = "https://osuny-dev-arkose.netlify.app/fr/actualites/2026-05-02-coupe-du-monde-descalade-2026-le-guide-complet-du-circuit-international/"

[[redirects]]
from = "/actualites/2026-05-04-portrait-de-jules-marchaland-linstinct-sauvage-rejoint-les-arkose-heroes/index.html"
to = "https://osuny-dev-arkose.netlify.app/fr/actualites/2026-05-04-portrait-de-jules-marchaland-linstinct-sauvage-rejoint-les-arkose-heroes/"

